name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -race ./...
    - name: Vet
      run: go vet ./...
    - name: Mod verify
      run: go mod verify
    - name: Staticcheck
      run: |
        go get honnef.co/go/tools/cmd/staticcheck
        staticcheck ./...
